apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/ThjmJkp0amHz1Hyk6k840KemGnHDPaW3uP+3g==,iv:b71kYBeg11fchhrzxE6EHa/BD2rDY+URWQfLQZs6h6A=,tag:9Q+f7N2J0ln3u0FqlHS+Cg==,type:str]
    AWS_DB_ACCESS_KEY_ID: ENC[AES256_GCM,data:BViH0B00wH735VsTqgo9gPEFO++B08LIeebJIg==,iv:xy8LByiTFVdloukUalUab1OooH2DgQQ5BbSXfdHxduY=,tag:5exygphjsJ/WokZYkmYmdQ==,type:str]
    AWS_DB_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:B5avDEHvr5biZB7GUaPPIMv2AlYPJkJ3NWFjUnN7r+DSaCLoicJzA6Xug2e05R154Hs/+7T3ptQ=,iv:vcHHN19QAzeatBErs3OioBZcKOD135GAmc11lPMpJ0E=,tag:DGinegH76WK6GkxrQK0V+g==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:K9SaoBHy+hzYPIeB,iv:JyT221pP6XD4h1viv/KdPk2bHuV69BFTkLzbs+T1Cdw=,tag:rgEDZwjsE+CcmQmdm4ApoA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/FEYsC1V7Yq8ioYsuHGaTFUdParP52eMQ/k3dd2SJyTd/qokIBHmyaPbit+Ja/3sgM/yoz+H/aI=,iv:t+bc9CcnLxVISAi7rUreCiqX5aBI4UiY6vavriOm/Z8=,tag:xHpSBSONlVSKPbkXktmaXA==,type:str]
    SERVICE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:RR7HuHH5Q6cWhRQ7g06SgweIhncluW+ujCe1Tw==,iv:i29ZtNj1oOSBnHJzGsXmmV4kBjgP1WELSUQqXLQfe14=,tag:/A7nWfCAoUZoJ/FG35eLRA==,type:str]
    SERVICE_ACCOUNT_USERNAME: ENC[AES256_GCM,data:HHUSoyYPMCl4JhIJzb959dy02Yw=,iv:wTkLvRfF++8F9dtNnlzyWQttVDEzDUeYYTfRHWe0fT8=,tag:PLSdFzmcxKyFyVs6FK7XXg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: prioritized-agenda-api-env-secret
    namespace: prioritized-agenda-sensing-production
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-20T12:44:16Z"
    mac: ENC[AES256_GCM,data:YXo0Dzes75n56Dgl48wK+3YwPf5oSvuXZ6sRKBTbKZWvmSELiJvp80yhfjLtsOiG2Co0J0w+xLVP4DDcomW8v8LyHryBusic+3ONHFMxFmctGNae8ndRhYBM2ul8ThdIuAa1soeEuqBjp4Az0qHEvtXyf3MVCP3Se0jTre4aayc=,iv:zFUlM1xTk3Hk2kX6b5mm0e/PV6KEPvW5qZNQjbai2RI=,tag:754asnye2RRH4aFea/DN7g==,type:str]
    pgp:
        - created_at: "2023-04-20T12:44:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAz9KIM96sM/oAQ/9FIxVu0vj5Jhc6MROlR1QOMAZad8CvJjt80wfEUjWmWVy
            +3kbKtRzyLZKrd+pOw/Ondqol/Ew98SIs+p6RTnMVSGz3Hudo4ySF9TMl/SLFAlA
            lqZHQyolB9GwULS4KPckW2dkmQjBhlnefJJCO3e3vn/tpq0PFAp6NNDyhzI2sxVp
            r2hUqCS+5GtrN/8xBi8gXZ7e/DmqpDrMosYwUKcC35Tj/gByW8uAHVBxbfCvALU/
            7Bv1r1DAH0H8GyuXAYXpIxfrIabzlXUxEXq9VHpvJBUAmrb6H/CiW2JNyNC/w88H
            bP2NMG70InRun1JDn5zdt2dWPnKaeT9eV3QyAG2Rne4J8CbbsvEaH+mg0PCtIDQD
            Clk3pYZErtsHUTY6xhpoo3ZT91AWA6qqwCtdQDta56N/nnW/eIDcrqVxHwsd68q/
            PYYqInUOTkZ4X8aZgknpcNeSxXCdK+jc9kcvkWT+cOVf1pYVjPREoSZc57cUmoFz
            IztO02v6zQ2c59r22obaaXmQ7UznMcUg/RUQ15HFVMI3bRLVgLsfeGTkvXQyWDiY
            7lgbGbmfTDpWZFoejEAbAxboG6LKotsBLnEQwN4yC/GIcX/CmPYn5pLhF+XWdXS1
            7R38LsFBuPEY2pvZPX5JdfuC292mpuFa0cSB2vXp6GvwK5nTcVDiejj5/DiuOuzS
            UQENAQMZTAnPcDx2ka/I2aaEVvmJR0z8I+Z3gy5j+9IT3IMIHLmytOK6vPm/U65w
            vR1YMf0Zigk3T6asSbN7SoxeLEw/N76W+3utFFRCrmgLFw==
            =b61H
            -----END PGP MESSAGE-----
          fp: 0795FD130E449AE6C8F7501A88143B8F9A6EEC55
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
