apiVersion: v1
kind: Pod
metadata:
  name: awscli
  labels:
    app: awscli
spec:
  serviceAccountName: prioritized-agenda-api
  containers:
    - name: awscli
      image: amazon/aws-cli
      command:
        - "sleep"
        - "604800"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512M
      env:
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: prioritized-agenda-api-map
              key: BUCKET_NAME
        - name: PA_ENV
          valueFrom:
            configMapKeyRef:
              name: prioritized-agenda-api-map
              key: PA_ENV
        # - name: AWS_DEFAULT_REGION
        #   valueFrom:
        #     secretKeyRef:
        #       name: prioritized-agenda-api-env-secret
        #       key: AWS_DEFAULT_REGION
        #       optional: false
        # - name: AWS_ACCESS_KEY_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: prioritized-agenda-api-env-secret
        #       key: AWS_ACCESS_KEY_ID
        #       optional: false
        # - name: AWS_SECRET_ACCESS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: prioritized-agenda-api-env-secret
        #       key: AWS_SECRET_ACCESS_KEY
        #       optional: false
        - name: AWS_DB_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: prioritized-agenda-api-env-secret
              key: AWS_DB_ACCESS_KEY_ID
              optional: false
        - name: AWS_DB_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: prioritized-agenda-api-env-secret
              key: AWS_DB_SECRET_ACCESS_KEY
              optional: false               
        - name: SERVICE_ACCOUNT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prioritized-agenda-api-env-secret
              key: SERVICE_ACCOUNT_PASSWORD
              optional: false               
        - name: SERVICE_ACCOUNT_USERNAME
          valueFrom:
            secretKeyRef:
              name: prioritized-agenda-api-env-secret
              key: SERVICE_ACCOUNT_USERNAME
              optional: false               
  restartPolicy: Always
