apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: prioritized-agenda-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prioritized-agenda-api
  minReplicas: 4
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 85
