---
apiVersion: v1
kind: Service
metadata:
  name: prioritized-agenda-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: prioritized-agenda-api
  type: ClusterIP
