apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prioritized-agenda-api
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: pipeline-api
  updatePolicy:
    updateMode: "Off"
